### ISSUE TITLE
Options page for turning refactorings on and off one by one.

### ISSUE THREAD

**Issue by maraf** [JosefPihrt/Pihrtsoft.CodeAnalysis#4]
Please consider some sort of configuration for turning single refactorings on and off.
It could be for example kind of options page or simple configuration file at a solution level.

**Comment by JosefPihrt** [comment]
dotnet/roslyn#4032

**Comment by wmjordan** [comment]
Before VS has implemented that feature. Could you please add some configuration support for the analyzer?
Even a text configuration file without UI can help.
I want to disable all "Remove..." refactorings.

**Comment by jnyrup** [comment]
Could you add a similar options page for the analyzers?
